### ISSUE TITLE
I tried downloading the code to edit some stuff and help commit but there's a bunch of compiler issues.

### ISSUE THREAD

**Issue by TheBagelBird** [Mukarillo/UnityPacman#5]
![image](https://user-images.githubusercontent.com/83887148/177047818-db003cbf-f5f9-4350-a9e5-ff3a42757ef9.png)

**Comment by Mukarillo** [comment]
Hey,

Thanks for the message, I fixed the issue with the latest commit. Please pull and it should be fixed.
